package cn.edu.guet.bean;

import java.io.Serializable;
import java.util.Date;

public class Permission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.PERMISSION_ID
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.PARENT_PERMISSION_ID
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private Integer parentPermissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.PERMISSION_NAME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.URL
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.TARGET
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.ICON
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.IS_PARENT
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private String isParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.CREATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.CREATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.UPDATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.UPDATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.PERMISSION_ID
     *
     * @return the value of permissions.PERMISSION_ID
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Permission withPermissionId(Integer permissionId) {
        this.setPermissionId(permissionId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.PERMISSION_ID
     *
     * @param permissionId the value for permissions.PERMISSION_ID
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.PARENT_PERMISSION_ID
     *
     * @return the value of permissions.PARENT_PERMISSION_ID
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Integer getParentPermissionId() {
        return parentPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Permission withParentPermissionId(Integer parentPermissionId) {
        this.setParentPermissionId(parentPermissionId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.PARENT_PERMISSION_ID
     *
     * @param parentPermissionId the value for permissions.PARENT_PERMISSION_ID
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setParentPermissionId(Integer parentPermissionId) {
        this.parentPermissionId = parentPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.PERMISSION_NAME
     *
     * @return the value of permissions.PERMISSION_NAME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Permission withPermissionName(String permissionName) {
        this.setPermissionName(permissionName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.PERMISSION_NAME
     *
     * @param permissionName the value for permissions.PERMISSION_NAME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.URL
     *
     * @return the value of permissions.URL
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Permission withUrl(String url) {
        this.setUrl(url);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.URL
     *
     * @param url the value for permissions.URL
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.TARGET
     *
     * @return the value of permissions.TARGET
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Permission withTarget(String target) {
        this.setTarget(target);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.TARGET
     *
     * @param target the value for permissions.TARGET
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.ICON
     *
     * @return the value of permissions.ICON
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Permission withIcon(String icon) {
        this.setIcon(icon);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.ICON
     *
     * @param icon the value for permissions.ICON
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.IS_PARENT
     *
     * @return the value of permissions.IS_PARENT
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public String getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Permission withIsParent(String isParent) {
        this.setIsParent(isParent);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.IS_PARENT
     *
     * @param isParent the value for permissions.IS_PARENT
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setIsParent(String isParent) {
        this.isParent = isParent == null ? null : isParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.CREATED_BY
     *
     * @return the value of permissions.CREATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Permission withCreatedBy(String createdBy) {
        this.setCreatedBy(createdBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.CREATED_BY
     *
     * @param createdBy the value for permissions.CREATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.CREATED_TIME
     *
     * @return the value of permissions.CREATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Permission withCreatedTime(Date createdTime) {
        this.setCreatedTime(createdTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.CREATED_TIME
     *
     * @param createdTime the value for permissions.CREATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.UPDATED_BY
     *
     * @return the value of permissions.UPDATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Permission withUpdatedBy(String updatedBy) {
        this.setUpdatedBy(updatedBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.UPDATED_BY
     *
     * @param updatedBy the value for permissions.UPDATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.UPDATED_TIME
     *
     * @return the value of permissions.UPDATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Permission withUpdatedTime(Date updatedTime) {
        this.setUpdatedTime(updatedTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.UPDATED_TIME
     *
     * @param updatedTime the value for permissions.UPDATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", permissionId=").append(permissionId);
        sb.append(", parentPermissionId=").append(parentPermissionId);
        sb.append(", permissionName=").append(permissionName);
        sb.append(", url=").append(url);
        sb.append(", target=").append(target);
        sb.append(", icon=").append(icon);
        sb.append(", isParent=").append(isParent);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append("]");
        return sb.toString();
    }
}