package cn.edu.guet.bean;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USER_ID
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USERNAME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.PASSWORD
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.CREATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.CREATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.UPDATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.UPDATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USER_ID
     *
     * @return the value of users.USER_ID
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public User withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USER_ID
     *
     * @param userId the value for users.USER_ID
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USERNAME
     *
     * @return the value of users.USERNAME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public User withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USERNAME
     *
     * @param username the value for users.USERNAME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.PASSWORD
     *
     * @return the value of users.PASSWORD
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public User withPassword(String password) {
        this.setPassword(password);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.PASSWORD
     *
     * @param password the value for users.PASSWORD
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.CREATED_BY
     *
     * @return the value of users.CREATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public User withCreatedBy(String createdBy) {
        this.setCreatedBy(createdBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.CREATED_BY
     *
     * @param createdBy the value for users.CREATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.CREATED_TIME
     *
     * @return the value of users.CREATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public User withCreatedTime(Date createdTime) {
        this.setCreatedTime(createdTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.CREATED_TIME
     *
     * @param createdTime the value for users.CREATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.UPDATED_BY
     *
     * @return the value of users.UPDATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public User withUpdatedBy(String updatedBy) {
        this.setUpdatedBy(updatedBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.UPDATED_BY
     *
     * @param updatedBy the value for users.UPDATED_BY
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.UPDATED_TIME
     *
     * @return the value of users.UPDATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public User withUpdatedTime(Date updatedTime) {
        this.setUpdatedTime(updatedTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.UPDATED_TIME
     *
     * @param updatedTime the value for users.UPDATED_TIME
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jul 17 17:14:50 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append("]");
        return sb.toString();
    }
}